baseURL: https://chcc1.netlify.app/
languageCode: en-us
title: CHCC
theme: oldpapermod
enableGitInfo: true
paginate: 10
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - date
    - publishDate
params:
  description: Equipping those called to serve and engage the Chinese heritage church.
  datesinlist: 1
  disableThemeToggle: false
  defaultTheme: light # dark, light, auto
  ShowReadingTime: false
  mainSections:
  - posts
# Using "posts" only (and not "pages") as a hack to only show the main image on the front page.



related:
  includeNewer: true
  threshold: 75
  toLower: false
  indices:
    - name: keywords
      weight: 100
    - name: date
      weight: 10
      
menu:
  main:
    - identifier: 123
      name: 123
      url: /about/
      weight: 10


imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 75
  resampleFilter: Box